# Generated by Django 4.2.6 on 2023-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_opcaoselecionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='opcoes_processo',
            field=models.JSONField(default=list),
        ),
    ]
