# Generated by Django 4.2.6 on 2023-11-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cliente_opcoes_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipos_processo',
            field=models.ManyToManyField(to='users.tipoprocesso'),
        ),
    ]
