# Generated by Django 4.2.6 on 2023-12-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cliente_tipos_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
