# Generated by Django 4.2.6 on 2023-12-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_processo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaoselecionada',
            name='processo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.processo'),
            preserve_default=False,
        ),
    ]
