# Generated by Django 4.2.6 on 2023-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaCorretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_corretor', models.CharField(max_length=100)),
                ('valor_faltante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
