# Generated by Django 4.2.6 on 2023-12-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vendacorretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.proprietario', verbose_name='Proprietário'),
            preserve_default=False,
        ),
    ]
