# Generated by Django 4.2.6 on 2023-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_processo_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, choices=[('aguardando_aprovacao', 'Aguardando Aprovação'), ('documentacao_pendente', 'Documentação Pendente'), ('aguardando_cancelamento_qv', 'Aguardando Cancelamento QV'), ('cliente_aprovado', 'Cliente Aprovado'), ('proposta_apresentada', 'Proposta Apresentada'), ('visita_efetuada', 'Visita Efetuada'), ('fechamento_proposta', 'Fechamento Proposta'), ('pagamento_tsd', 'Pagamento TSD'), ('conformidade', 'Conformidade'), ('assinatura_minuta_caixa', 'Assinatura Minuta Caixa'), ('comissao_recebida', 'Comissão Recebida'), ('concluido', 'Concluído'), ('reprovado', 'Reprovado'), ('Não Deu continuidade', 'Não Deu continuidade')], default='aguardando_aprovacao', max_length=50, null=True),
        ),
    ]
