# Generated by Django 4.2.6 on 2023-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_cliente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='remdautilizada',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
