# Generated by Django 4.2.6 on 2023-12-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_cliente_remdautilizada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='remdautilizada',
            new_name='Renda',
        ),
    ]
