# Generated by Django 4.2.6 on 2023-12-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_remdautilizada_cliente_renda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Renda',
            new_name='valor_da_renda',
        ),
    ]
