# Generated by Django 4.2.6 on 2023-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_renda_cliente_valor_da_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_da_renda',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
